### ISSUE TITLE
fprime-util build fails

### ISSUE THREAD

**Issue by rwilbur** [fprime-community/fprime-tutorial-hello-world#14]
I tried following all of the instructions within the tutorial. When I go to build I end up with this error. I double checked the component and deployment were all created in accordance with the tutorial. I would love to be told it is just user error but I'm not sure how to fix this error.

I am running Ubuntu 22.04 LTS, using CMake 3.22.1, python 3.10.12 in a venv as created in the tutorial.

`gmake[3]: *** No rule to make target 'HelloWorldDeployment/Top/HelloWorldDeploymentTopologyAppAi.xml', needed by 'Components/HelloWorldDeployment/Top/HelloWorldDeploymentPacketsAc.cpp'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:5253: Components/HelloWorldDeployment/Top/CMakeFiles/Components_HelloWorldDeployment_Top.dir/all] Error 2
`

**Comment by strott** [comment]
I have encountered the same issue in the helloworld tutorial. @rwilbur were you able to figure out what was going on?

**Comment by rwilbur** [comment]
@strott Unfortunately I had other stuff I needed to take care of so couldn't do a deep dive into what was going on so I don't have anything helpful for you.

**Comment by thomas-bc** [comment]
If the error message shows 
```
[...] Components/HelloWorldDeployment/Top/[...]
```
you have created the deployment in the wrong directory. Please `cd` back at the top level of the project, and run `fprime-util new --deployment` there. You may have to remove the line `add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/HelloWorldDeployment/")` in  `Components/CMakeLists.txt`
