### ISSUE TITLE
Need to generate in HelloWorldDeployment 

### ISSUE THREAD

**Issue by hAkselS** [fprime-community/fprime-tutorial-hello-world#6]
In the developing deployments section of this tutorial, users are asked to build the deployment directory before generating a build cache. This happens right before running fprime-gds.

**Comment by capsulecorplab** [comment]
Opened an issue about this in https://github.com/nasa/fprime/issues/2133

**Comment by thomas-bc** [comment]
Resolved as of v3.3.0
